### ISSUE TITLE
captha solving

### ISSUE THREAD

**Issue by FeelsBadMan1** [Matthew17-21/Captcha-Tools#1]
Hello, i tried to use this module for solving capthas but i dont know where i can get the sitekey and the captha_url....
Adittionaly it would be nice, if hcpatha support becomes added.

**Comment by Matthew17-21** [comment]
Hey,

- To locate a site's sitekey, [checkout this blog](https://2captcha.com/2captcha-api#solving_recaptchav2_new)
- The captha_url is the URL of where the captcha is located. For example, the captcha_url for [this site](https://www.google.com/recaptcha/api2/demo) would be `https://www.google.com/recaptcha/api2/demo`, and the sitekey would be `6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-`

As far HCaptcha support goes, I'll add it to the to-do list!

Closing this issue as I believe I answered everything.

**Comment by FeelsBadMan1** [comment]
OK most things are solved. Hoowever i still not know how i can get the sitekey i only know how a sitekey should look like....

**Comment by FeelsBadMan1** [comment]
ok thanks that hleped me. however if i run the script i get this error each time:
`Traceback (most recent call last):
  File "D:\my_python_projects\autobuy\main.py", line 21, in <module>
    captcha_answer = solver.get_token()
  File "D:\my_python_projects\Servercopy - Discordbot\venv\lib\site-packages\captchatools\harvesters.py", line 37, in get_token
    return self.harvester.get_token()
AttributeError: 'captcha_harvesters' object has no attribute 'harvester'`

**Comment by Matthew17-21** [comment]
What does your code look like? Which harvester are you using?

**Comment by FeelsBadMan1** [comment]
```
import time
import json
import captchatools

from captchatools import captcha_harvesters, exceptions as captchaExceptions
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
browser = webdriver.Chrome("D:\\my_python_projects\\autobuy\\chromedriver.exe")
website = "https://www.google.com/recaptcha/api2/demo"
geturl = browser.get(website)


try:
    with open("config.json") as configfile:
        config = json.load(configfile)
        captchaservice = config.get("Service")
        apikey = config.get("APIkey")

        solver = captchatools.captcha_harvesters(solving_site=captchaservice, api_key=apikey, sitekey="6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-",
                                                 captcha_url="https://www.google.com/recaptcha/api2/demo")
        captcha_answer = solver.get_token()
        print(captcha_answer)

except captchaExceptions.NoBalanceException:
    print(f"Your {captchaservice} account not have enough Money. Please go refill it!")

except captchaExceptions.WrongAPIKeyException:
    print("The API-Key is not correct. Please refer to config.json and check your API-Key!")

except captchaExceptions.WrongSitekeyException:
    print("The Sitekey is invalid!")

```

**Comment by Matthew17-21** [comment]
Just ran this code and got no issues.

Double check that in your `config.json` file, the `captchaservice` key is of the right type. 
- For example, it should be either `1` (int) or `"Capmonster"` (string). 
- If you were to enter `"1"`, it would throw the `AttributeError: 'captcha_harvesters' object has no attribute 'harvester'` error you have been seeing, 

After that, there shouldn't be anymore errors!

Refer to the [param list](https://github.com/Matthew17-21/Captcha-Tools#how-to-use) for their required types.

**Comment by FeelsBadMan1** [comment]
so i think my configfile is correct:
```
{
  "Service": "capmoster",
  "APIkey": "here was my apikey"
}
```

**Comment by Matthew17-21** [comment]
Almost is. Should be "capmonster", not "capmoster"

**Comment by FeelsBadMan1** [comment]
That solved the Attribute error. However after it visit the Website the captcha not become solved.

**Comment by FeelsBadMan1** [comment]
Helloagain. i think i almost solved it. WHat is the attribute to actually run it? i now only definied variables.
