### ISSUE TITLE
installation integration help

### ISSUE THREAD

**Issue by badplay** [Matthew17-21/Captcha-Tools#11]
hello i have a python tool with pyautogui and it log in a site, then there is the captcha

i dont understand to install this git
i installed the package and import it in the python file
i edded a def with example

`import captchatools
solver = captchatools.captcha_harvesters(solving_site="capmonster", api_key="YOUR API KEY", sitekey="6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-", captcha_url="https://www.google.com/recaptcha/api2/demo")
captcha_answer = solver.get_token()`

but what now how i tell the script use the captchatools to solve and go on with the script

**Comment by Matthew17-21** [comment]
> how i tell the script use the captchatools to solve and go on with the script

You are already telling the script to use captchatools when you include 
```py
import captchatools 
solver = captchatools.captcha_harvesters(solving_site="capmonster", api_key="YOUR API KEY", sitekey="6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-", captcha_url="https://www.google.com/recaptcha/api2/demo") 
captcha_answer = solver.get_token()
```
in your code.

To us the actual token that is returned from captchatools is a different story. Each website is different so really can't help there. It's best if you look at how/when/where the captcha token is being validated and to which endpoint on your site :)
