### ISSUE TITLE
Integration capsolver.com

### ISSUE THREAD

**Issue by Xeeeno** [Matthew17-21/Captcha-Tools#12]
Hey, it's possible that you integrate [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc...
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by Matthew17-21** [comment]
Already had them on my list to add 😄 

I'll see if I have some free time later to week to add n push

**Comment by Matthew17-21** [comment]
[Added in 1.3.0](https://github.com/Matthew17-21/Captcha-Tools/releases/tag/1.3.0)
