### ISSUE TITLE
Can you please add captchaai?

### ISSUE THREAD

**Issue by sxdfgnb** [Matthew17-21/Captcha-Tools#14]
Hi,

Can you please add support for Captchaai? Docs can be found here https://captchaai.com/api-docs.php

Thanks

**Comment by Matthew17-21** [comment]
I believe they rebranded to [Capsolver.](https://capsolver.com/)

[I just added support for Go](https://github.com/Matthew17-21/Captcha-Tools/commit/62b370497e15a7bbd8ef4b218f48279dd93b2d92). I'm going to work on the Py version soon.

**Comment by sxdfgnb** [comment]
Hi,

CaptchaAI is diffrent of captchas.io (capsolver now)
So please consider adding it in your next Update.
There are the same as 2Captcha API
https://captchaai.com/api-docs.php

**Comment by Matthew17-21** [comment]
[Added for the Go version](https://github.com/Matthew17-21/Captcha-Tools/commit/b8fbf82de1424f32a67e6faf6ceed395b6f00b01). Will try to get Py support done before the weekend. Lets see how that goes.

**Comment by Matthew17-21** [comment]
Added for Py in [1.4.1](https://github.com/Matthew17-21/Captcha-Tools/releases/tag/1.4.1).
