### ISSUE TITLE
Support for rqdata & rqtoken

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#20]
Whenever i request a specific discord api url i get following response which includes rqdata and rqtoken as shown below:
```py
        {
            "captcha_key":["Du musst deine App aktualisieren, um diesem Server beizutreten."],
            "captcha_sitekey":"a9b5fb07-92ff-493f-86fe-352a2803b3df",
            "captcha_service":"hcaptcha",
            "captcha_rqdata":"+PIKziyDja04lsUPMZV2v6fyfkEuk72TI/ZKxLth1GzbQ81z532xBuGK5U4GBJZV6ss2ivfpsw3BZTCySJ0hsQacbptBlkhEgeKeBlP6aZZM1zYpZyU9k+BKmbVwtXqBQRggxyA9eun/10j98zOxZAr6sudpBbLL/aPMqCiC",
            "captcha_rqtoken":"IjdVWlVEMWk0NlJtUjJUWGxpUmsrSXN3bUxJbTdTTWJ1SEVuSTE0QjFIanFPbk5IT2xTTGhSb1FDMGRVRVM4RFVjUDZVekE9PXAzMEt1K1Y2c0Zwdm1EcVQi.ZWDKZA.OfU1PsN0Cyk97jiVjDOdt_BJGt4"
        }
 ```
 
 Now, if i remember correctly, services like capsolver or anitcaptcha allow you to provide those in the solving request, yet i havn't fund such an option within the captchatools libary. would be great if anyone could help me out.
 
 Regards,
 FuckingToasters

**Comment by Matthew17-21** [comment]
Hi, hope all is well.

I thought I had already implemented that. Just double checked and you are right, that feature is missing.

That's a quick add so I can probably have that done before Monday, if everything works in my favor.

**Comment by FuckingToasters** [comment]
> Hi, hope all is well.
> 
> I thought I had already implemented that. Just double checked and you are right, that feature is missing.
> 
> That's a quick add so I can probably have that done before Monday, if everything works in my favor.

Thank you for your work in advance, appriciate it.
After you added it, would be nice if you could let it me know in this issue before you close it.

Regards,
FuckingToasters

**Comment by FuckingToasters** [comment]
I see in the pull requests that you did something with rqdata but it's not in the master branch so i can't update it via pip.

**Comment by Matthew17-21** [comment]
Yea my plan was to update PyPi today with the newer version 🙂

Btw, all of the solving sites seem to only allow for the `rqdata` and not `rqtoken` to be sent to them. I'm assuming that the token isn't needed by them.

**Comment by FuckingToasters** [comment]
> Yea my plan was to update PyPi today with the newer version 🙂
> 
> Btw, all of the solving sites seem to only allow for the `rqdata` and not `rqtoken` to be sent to them. I'm assuming that the token isn't needed by them.

Thank you for this update, i guess rqtoken is specific to discord and probably need to be passed when sending the solution to discord aswell but i haven't looked into this so far.

**Comment by Matthew17-21** [comment]
I know Anticaptcha accepts more params for Hcaptcha, if you look under their [enterprisePayload for hcaptcha](https://anti-captcha.com/apidoc/task-types/HCaptchaTaskProxyless). The only thing is none of the extra params are named `rqtoken`. If you one of those extra params is an alias for the `rqtoken`, i'll be happy to update it.
