### ISSUE TITLE
Captha Solving using capmonster

### ISSUE THREAD

**Issue by FeelsBadMan1** [Matthew17-21/Captcha-Tools#3]
Hello, i think i almost got it to work. however i searched a lot but i found no docs telling me what attribute im supposed to use so it actually solve the capthas. I only found how i need to define different variables. but variables alone wont run the module.... here this is the code i made so far. It prints the code out correctly but the issure is, it not solve the captha:
```
solver = captchatools.captcha_harvesters(solving_site="capmonster", api_key="my key where here", sitekey="6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-", captcha_url="https://www.google.com/recaptcha/api2/demo")
captcha_answer = solver.get_token()
print(captcha_answer)
```

**Comment by Matthew17-21** [comment]
Hi!

I copied your code and it ran without any issues. What seems to be the issue?

**Comment by Matthew17-21** [comment]
The timing of solving captchas vary by captcha site and captcha type. If everything is correct, it will output the captcha token, as shown below.

![](https://i.imgur.com/wkQ1rdR.png)

**Comment by FeelsBadMan1** [comment]
Hmm yea the token where printed into the terminal on my side too like i already wrote above. however the captcha not became solved. "It prints the code out correctly but the issure is, it not solve the captha:"

**Comment by Matthew17-21** [comment]
If the captcha token is being printed, that means the captcha is solved. Are you trying to use the token on a different site?

**Comment by FeelsBadMan1** [comment]
No. I use selenium and after the token is being printed, the window closes. The verified icon on the captcha box wont be added so i cant press on continue later on.

**Comment by Matthew17-21** [comment]
That's entirely different. You need to research how to use selenium with captcha tokens. From what I hear you need to change the element with the correct / solved token. 

There is nothing wrong with this module, it's functioning to the fullest extent. These tokens are best used when dealing with requests.

**Comment by FeelsBadMan1** [comment]
hmm okay. so how im able to use it with requests then? like what requests i need to do so it register a account on yandex for example? I looked up how i can insert the tokens in selenium but i found nothing useful....

**Comment by Matthew17-21** [comment]
I'd suggest starting with learning what request(s) are and how they work. Then learn how the website makes the request and then you implement something to replicate that.

**Comment by FeelsBadMan1** [comment]
hmm okay. ill try to learn requests

**Comment by FeelsBadMan1** [comment]
> That's entirely different. You need to research how to use selenium with captcha tokens. From what I hear you need to change the element with the correct / solved token.
> 
> There is nothing wrong with this module, it's functioning to the fullest extent. These tokens are best used when dealing with requests.

I understood how that should work and it works on some sites but on the site im trying to inject  the code it not will continue after its solved cause there is no button like "continue" if you solve it manually it add the checkmark and then directly continue without need to press a button but this is not possible using selenium i think however probably you understand how to solve this issue.
