### ISSUE TITLE
Libary is broken.

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#30]
Hello, so today i tried debugging for hours but couldn't find what causes the error i have.

Here my code:
```py
class Captcha:
    def __init__(self, service, apikey, url):
        self.service = service
        self.apikey = apikey
        self.url = url


        print("client.py:505: ", self.service, self.apikey, self.url)

    
    def get_token(self, sitekey, rqdata):
        print("Service being used:", self.service)

        if self.service == "nopecha":
            nopecha.api_key = self.apikey

            # Call the Token API
            captcha_answer = nopecha.Token.solve(
                type='hcaptcha',
                sitekey=sitekey,
                url=self.url,
                proxy={
                    'scheme': 'http',
                    'host': '127.0.0.1',
                    'port': '7234',
                    'username': 'REDACTED',
                    'password': 'REDACTED',
                }
            )
            return True, captcha_answer

        elif self.service == "fcb":
            from freecaptchabypass import FCBClient, HCaptchaTask

            client = FCBClient(self.apikey)
            print("client.py:531: ", client)


        else:
            import captchatools
            
            sitekey="4c672d35-0701-42b2-88c3-78380b0db560" # TEMPORARY, OVVERRIDES SITEKEY PASSED AS ARGUMENT => FORGOT PASSWORD ENDPOINT

            solver = captchatools.new_harvester(
                solving_site=self.service,
                api_key=self.apikey,
                sitekey=sitekey,
                captcha_url=self.url,
                captcha_type="hcaptcha"
            )

            try:
                captcha_answer = solver.get_token(rq_data=rqdata)
                return True, captcha_answer
                #return True, json.loads(captcha_answer) if type(captcha_answer) is not str else True, captcha_answer

            except captchatools.exceptions.WrongAPIKeyException:
                return False, "Incorrect API key for the captcha solving site"

            except captchatools.exceptions.NoHarvesterException as err:
                return False, "No solving site selected"
                
            except captchatools.exceptions.UnknownError as err:
                print(err)
                return False, str(err)
```

The Issue is that, somehow it always run the else block even if the service provided is being checked for in the above if blocks, this only happen when there is captchatools in the else block. a normal `print("hello world")` in the else block won't execute when the service is `fcb`.

I attached a screenshot of the Traceback.

Regards,
FuckingToasters

![grafik](https://github.com/user-attachments/assets/5809cbfe-aa20-4c3c-81be-bd101cde7bb6)

**Comment by Matthew17-21** [comment]
Not sure I'm understanding correctly.

Are you saying that if you have a setup such as the one below, it falls back to the else statement?
```py
c = Captcha("fcb", APIKEY, URL)
token = c.get_token(SITKEY, RQDATA)
print(token)
```

**Comment by Matthew17-21** [comment]
> Not sure I'm understanding correctly.
> 
> Are you saying that if you have a setup such as the one below, it falls back to the else statement?
> 
> ```python
> c = Captcha("fcb", APIKEY, URL)
> token = c.get_token(SITKEY, RQDATA)
> print(token)
> ```

Running this exact code in Python 3.12 branches to the correct statement. I got an error, but only because I don't have it installed:



```py
client.py:505:  fcb  
Service being used: fcb
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    token = c.get_token(SITKEY, RQDATA)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "test.py" line 33, in get_token
    from freecaptchabypass import FCBClient, HCaptchaTask
ModuleNotFoundError: No module named 'freecaptchabypass
```

**Comment by FuckingToasters** [comment]
> > Not sure I'm understanding correctly.
> > Are you saying that if you have a setup such as the one below, it falls back to the else statement?
> > ```python
> > c = Captcha("fcb", APIKEY, URL)
> > token = c.get_token(SITKEY, RQDATA)
> > print(token)
> > ```
> 
> Running this exact code in Python 3.12 branches to the correct statement. I got an error, but only because I don't have it installed:
> 
> ```python
> client.py:505:  fcb  
> Service being used: fcb
> Traceback (most recent call last):
>   File "test.py", line 72, in <module>
>     token = c.get_token(SITKEY, RQDATA)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "test.py" line 33, in get_token
>     from freecaptchabypass import FCBClient, HCaptchaTask
> ModuleNotFoundError: No module named 'freecaptchabypass
> ```

nvm, i built my discord sdk libary without being in the correct venv haha. works now.
