### ISSUE TITLE
Normal Image Captcha

### ISSUE THREAD

**Issue by Vinyzu** [Matthew17-21/Captcha-Tools#4]
Is it possible to solve captchas like this?'
https://captcha.com/images/captcha/180/botdetect-captcha-negative.jpg

**Comment by Matthew17-21** [comment]
Added in update [1.2.1](https://github.com/Matthew17-21/Captcha-Tools/releases/tag/1.2.1)

Don't forget to update:
```
pip3 install -U captchatools
```
