### ISSUE TITLE
Mail.ru Sitekey

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#6]
Hello, i read the existing issues and the blog how to obtain the sitekey. this worked on google but i can not find the sitekey on mail.ru
I found out that they just show a url that generate the captcha each tme and display it into the frame [Mail.ru Captcha Generation Website](https://c.mail.ru/c/0?r=0.5546017180093742) I then thought that within the URL at r=0.5546017180093742 the sitekey is 0.5546017180093742 but this was not the case as i got this Traceback: captchatools.exceptions.WrongSitekeyException: [captchatools] Incorrect google sitekey

Here the code i have so far:
```py
elif option == "8":
    url="https://e.mail.ru/settings/aliases"

    headers = {
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 OPR/81.0.4196.31",
        "Content-Type": "application/json"

    }
    data = {
        "username": "example@mail.ru",
        "Login": "example@mail.ru",
        "password": "secret",
        "Password": "secret",
        "saveauth": "1"
    }

    response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response)
    solver = captcha_harvesters(solving_site=1, api_key="here_was_my_key",
                                sitekey="0.5546017180093742",
                                captcha_url="https://c.mail.ru/c/0?r=0.5546017180093742")
    prnt("Solving the Captcha...")
    captcha_answer = solver.get_token()
    print(captcha_answer)
    ```

**Comment by Matthew17-21** [comment]
You are correct, `0.5546017180093742` is not the sitekey. Google sitekeys usually look like this `"6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-`. 

[Read this documentation how to locate a sitekey.](https://2captcha.com/2captcha-api#solving_recaptchav2_new)

**Comment by FuckingToasters** [comment]
> You are correct, `0.5546017180093742` is not the sitekey. Google sitekeys usually look like this `"6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-`.
> 
> [Read this documentation how to locate a sitekey.](https://2captcha.com/2captcha-api#solving_recaptchav2_new)

Yes, that is what i thought already and im aware how a sitekey should usually look i also read the documentation already however i still cant find it meanwhile on the google demosite its easy to find.
