### ISSUE TITLE
Callback-Function

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#7]
Hello, i read the article https://2captcha.com/2captcha-api#solving_recaptchav2_new and because the site, where i try to solve the captcha do not have a button that need to be pressed after the captcha is solved, it tells me that i need to call a callbackfunction. However i do not find the name of this function on the Website. Does anyone probably could tell me what the callbackfunction from discord.com/register is? Would be really kind.

**Comment by Matthew17-21** [comment]
I have to close this because this issue isn't related to this module. Sorry.
