### ISSUE TITLE
Invalid Sitekey error even tho it's correct.

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#8]
Hello, i used capmonster so far and the invalid Sitekey issue did not happen however capmonster is flagged on my target so i started using 2captcha which then gave me the invalid Sitekey error. I then checked if the Sitekey is correct and it is. Is there any solution for it? Complete errorlog:
```py
File "/usr/local/lib/python3.9/site-packages/captchatools/twocap.py", line 64, in get_id
    raise captchaExceptions.WrongSitekeyException()
captchatools.exceptions.WrongSitekeyException: [captchatools] Incorrect google sitekey
```

**Comment by Matthew17-21** [comment]
The only way I can take a look at it is if the sitekey is provided, but I don't think i'll be able to do much given that the exception is automatically thrown based on 2captcha's response. So, it's 2captcha that thinks the sitekey is invalid.

Are you sure you selected the correct captcha type for the sitekey?

**Comment by FuckingToasters** [comment]
> The only way I can take a look at it is if the sitekey is provided, but I don't think i'll be able to do much given that the exception is automatically thrown based on 2captcha's response. So, it's 2captcha that thinks the sitekey is invalid.
> 
> Are you sure you selected the correct captcha type for the sitekey?

This is the configurationfile. The Sitekey works finew ith capmonster but capmonster is flagged so i'm trying to use 2captcha
{
  "Captcha Stuff": {
    "Captcha Service": "2captcha",
    "Captcha Service ApiKey": "",
    "Site Key": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"
  }
}

**Comment by Matthew17-21** [comment]
Make sure you set the correct captcha type for the harvester. I just ran this code and got an answer without any exceptions.

```py
import captchatools
solver = captchatools.captcha_harvesters(solving_site=3, api_key="UPDATE THIS", captcha_type="hcap", sitekey="f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", captcha_url="https://discord.com/register")
captcha_answer = solver.get_token()
print(captcha_answer)
```

**Comment by Matthew17-21** [comment]
Haven't heard back from you so I assume everything is working.

Closing.

**Comment by FuckingToasters** [comment]
Hi, yes I forgot to let you know that after adding the type everything is working. Seems like the type is not needed for capmonster. However thank you for helping me out 😉
