### ISSUE TITLE
another service you should consider adding to the api

### ISSUE THREAD

**Issue by yaar007** [Matthew17-21/Captcha-Tools#9]
they have good solving rate https://nocaptchaai.com

**Comment by FuckingToasters** [comment]
ye would be nice to have this one

**Comment by Matthew17-21** [comment]
So I checked out the documentation and it seems that service doesn't return valid Hcaptcha tokens, rather, they return instructions on where to click on the captcha to solve it. Meaning, it seems that this service is geared towards more browser based bots.

If what I said above is correct and they actually don't return valid tokens, not 100% sure if this is something i'd want to incorporate to this module. But we'll see.

Also, if you are using Go I update the module to 2.0.0 so check it out 😄

**Comment by FuckingToasters** [comment]
> So I checked out the documentation and it seems that service doesn't return valid Hcaptcha tokens, rather, they return instructions on where to click on the captcha to solve it. Meaning, it seems that this service is geared towards more browser based bots.
> 
> If what I said above is correct and they actually don't return valid tokens, not 100% sure if this is something i'd want to incorporate to this module. But we'll see.
> 
> Also, if you are using Go I update the module to 2.0.0 so check it out smile

https://nocaptchaai.com/ have some usage examples for python requests which indeed return a valid hcaptcha token: https://github.com/shimuldn/hCaptchaSolverApi/blob/main/usage_examples/python_requests_with_Playwright.py

This example code would need to be edited to fit in the libary and maybe update the motiondata values cause i guess they are flagged by sites like discord but i'm not 100% sure about that.

**Comment by Matthew17-21** [comment]
Good catch. I was looking at the [response of a successfully solved captcha](https://github.com/shimuldn/hCaptchaSolverApi/blob/main/usage_examples/successfully-solved.json) and I was like yea that's def not going to cut it lol. I guess that changes my perspective on it.

As far as motion data goes, it seems that it [might not be a requirement according to their docs?](https://docs.nocaptchaai.com/Methods/solve#post-solve-requests) Even if it were to be required, I suppose I can leave that to the user. That way they can provide either spoofed or real motion data.

@yaar007 I'm assuming you've used this service before? Any comments with regards to motion data and such?

**Comment by Matthew17-21** [comment]
[Added in 1.3.0](https://github.com/Matthew17-21/Captcha-Tools/releases/tag/1.3.0)
